name: Build Docker Image
on: workflow_dispatch

jobs:
    build:
      name: push docker image to docker hub
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: login to docker hub
          id: docker-hub
          env:
            username: ${{secrets.DOCKERHUB_USERNAME}}
            password: ${{secrets.DOCKERHUB_PASSWORD}}
          run: |
            docker login -u $username -p $password 
        - name: build the docker image
          id: build-docker-image
          run: |
            docker build -t coder-anaconda-python3 .
            docker tag coder-anaconda-python3 lulasakamoto204/coder-anaconda-python3:latest
            docker push lulasakamoto204/coder-anaconda-python3:latest
        - name: push the docker image
          id: push-docker-image
          run: docker push ${{secrets.DOCKERHUB_USERNAME}}/coder-anaconda3-ipython:latest
